#!/usr/bin/env node

const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.resolve(__dirname, "..");

const SELECTED_KEYS = [
  "APP_ENV",
  "API_BASE_URL",
  "R2_PUBLIC_BASE",
  "PORT",
  "APP_PORT",
  "POSTGRES_USER",
  "POSTGRES_PASSWORD",
  "POSTGRES_DB",
  "DATABASE_URL",
  "JWT_SECRET",
  "OPENAI_API_KEY",
  "OPENAI_MODEL",
  "API_KEY",
  "RATE_LIMIT_WINDOW_MS",
  "RATE_LIMIT_MAX",
  "AUTH_RATE_LIMIT_WINDOW_MS",
  "AUTH_RATE_LIMIT_MAX",
  "PG_POOL_MAX",
  "R2_ACCOUNT_ID",
  "R2_ACCESS_KEY_ID",
  "R2_SECRET_ACCESS_KEY",
  "R2_BUCKET",
  "APP_UPDATE_MANIFEST_URL"
];

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return {};
  }

  return fs
    .readFileSync(filePath, "utf8")
    .split(/\r?\n/)
    .reduce((env, line) => {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) {
        return env;
      }

      const separatorIndex = trimmed.indexOf("=");
      if (separatorIndex < 0) {
        return env;
      }

      const key = trimmed.slice(0, separatorIndex).trim();
      const rawValue = trimmed.slice(separatorIndex + 1).trim();
      const value = rawValue.replace(/^["']|["']$/g, "");
      return key ? { ...env, [key]: value } : env;
    }, {});
}

function hasOwn(env, key) {
  return Object.prototype.hasOwnProperty.call(env, key);
}

function selectedValue(fileEnv, key) {
  if (hasOwn(fileEnv, key)) {
    return fileEnv[key];
  }

  return process.env[key] ?? "";
}

function quoteEnv(value) {
  if (!value) {
    return "";
  }
  return JSON.stringify(value);
}

function envName(value) {
  return value === "production" || value === "prod" ? "prod" : "dev";
}

const suffix = envName(process.env.APP_ENV);
const fileEnv = {
  ...parseEnvFile(path.join(ROOT, `.env.${suffix}`)),
  ...parseEnvFile(path.join(ROOT, `.env.${suffix}.local`))
};
const appEnv = suffix === "prod" ? "production" : "development";

console.log(`# Generated by scripts/select-env.cjs for ${appEnv}`);
console.log(`APP_ENV=${appEnv}`);

for (const key of SELECTED_KEYS) {
  if (key === "APP_ENV") {
    continue;
  }

  const value = selectedValue(fileEnv, key);
  console.log(`${key}=${quoteEnv(value)}`);
}
